-- Generated by hyprmonitor
-- Last updated: 2026-09-16T01:28:01
-- Do not edit manually — use the hyprmonitor GUI or create monitors.lua to override

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144.002",
    position = "-1640x-320",
    scale    = 1.25,
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@100",
    position = "-104x-198",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@74.973",
    position = "1816x-165",
    scale    = 1.0,
})

-- Fallback: any unrecognized monitor gets best available mode
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.0,
})
