git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
  diffContextSize: 10
keybinding:
  files:
    toggleStagedAll: A
gui:
  expandFocusedSidePanel: true
  mainPanelSplitMode: vertical
  sidePanelWidth: 0.25
  theme:
    activeBorderColor:
      - green
      - bold
